runtime: python37

entrypoint: gunicorn --bind 0.0.0.0:$PORT -c gunicorn_conf.py main:app

handlers:
- url: /
  static_files: static/index.html

- url: /static
  static_dir: static/

- url: /.*
  script: auto
  secure: always
